resources:
  - ../../base

# Add a suffix to distinguish dev environment
nameSuffix: -dev

# Override image tag for dev deployment
images:
  - name: pavankalyan787/nginx-webapp 
    newTag: dev-latest
